#ifndef RENDERING_API_H
#define RENDERING_API_H

#include <stdinc.h>
#include <assert.h>
#include <atomic.h>
#include <audio.h>
#include <bits.h>
#include <blendmode.h>
#include <clipboard.h>
#include <cpuinfo.h>
#include <endian.h>
#include <error.h>
#include <events.h>
#include <filesystem.h>
#include <gamepad.h>
#include <guid.h>
#include <haptic.h>
#include <hidapi.h>
#include <hints.h>
#include <init.h>
#include <joystick.h>
#include <keyboard.h>
#include <keycode.h>
#include <loadso.h>
#include <locale.h>
#include <log.h>
#include <messagebox.h>
#include <metal.h>
#include <misc.h>
#include <mouse.h>
#include <mutex.h>
#include <pixels.h>
#include <platform.h>
#include <power.h>
#include <_properties.h>
#include <quit.h>
#include <rect.h>
#include <render.h>
#include <rwops.h>
#include <scancode.h>
#include <sensor.h>
#include <surface.h>
#include <system.h>
#include <thread.h>
#include <timer.h>
#include <touch.h>
#include <version.h>
#include <video.h>
#include "video_capture.h"
#include <oldnames.h>
#endif
#endif /* SDL_h_ *
